server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/playground
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

# Challenge 2: Fixed DB Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=10

# Dynamic Thread Config
server.tomcat.threads.max=${TOMCAT_THREADS_MAX:200}
